# Solving Linear Regression 

In [1]:
import numpy as np
import pickle

In [2]:
# load
with open('data.pickle', 'rb') as f:
    data_load = pickle.load(f)

In [3]:
X, y = data_load

### Analytic Solution

Let $X \in \mathbb{R}^{(d+1) \times N}$ be the ***design matrix*** of the data,
that is, the $i$th row vector of $X$ is $\hat{x^i} = (1, x^i)$.

Let $y \in \mathbb{R}^N$ be the vector consisting of labels of data.

Then, the loss function $L(w)$ can be written as the following vector notation:
$$ L(w) = \frac{1}{2N} \| y- Xw \|^2 = \frac{1}{2N} (y-Xw)^\top (y-Xw).$$

Since the loss function is convex w.r.t $w$, we can find the minimum by differentiating the function w.r.t $w$.

$$ \frac{\partial L}{\partial w} (y^\top y - 2y^\top Xw + w^\top X^\top Xw) = -2X^\top y + 2X^\top X w = 0$$

Therefore, if $X^\top X$ is invertible, the analytic solution is
$$ w = (X^\top X)^{-1} (X^\top y). $$

In [4]:
w = np.linalg.solve(X.T@X, X.T@y)

In [5]:
w

array([[ 0.56088936],
       [-4.00333695],
       [ 3.66897589],
       [-6.52550363]])

It's Wrong!

In [6]:
Z = np.zeros((X.shape[0], X.shape[1]+1))

In [7]:
for i in range(X.shape[0]):
    temp = list(X[i])
    temp.insert(0, 1)  #List.insert(index, value) index에 value값을 넣기
    Z[i] = np.array(temp)

In [8]:
w = np.linalg.solve(Z.T@Z, Z.T@y)

In [9]:
w

array([[10.03357217],
       [ 3.00915189],
       [-4.00333695],
       [ 1.00309003],
       [-6.99128192]])

### Gradient Descent Method

In [9]:
INPUT_DIM=4
OUTPUT_DIM=1

In [13]:
params = {'W': np.random.randn(4,1),
         'b': np.zeros(1)}

In [14]:
def forward(X, params):
    out = np.matmul(X, params['W']) + params['b']
    return out

In [17]:
X.shape

(3360, 4)

### Gradient Descent

In [33]:
EPOCHS=300
lr=0.00001

In [34]:
Z.shape

(3360, 5)

In [35]:
weights = np.zeros(5)

In [36]:
def forward_pass(X,w):
    return X.dot(w)

In [37]:
def compute_gradient(X,y,w):
    y_hat = forward_pass(X,w)
    return X.T@(y_hat-y)

In [38]:
for _ in range(EPOCHS):
    weights -= lr*compute_gradient(Z,y,weights)

In [39]:
weights

array([ 9.84495223,  2.92013249, -3.99766007,  1.0455666 , -7.00999904])