# Solving Linear Regression 

In [1]:
import numpy as np
import pickle

In [2]:
# load
with open('data.pickle', 'rb') as f:
    data_load = pickle.load(f)

In [5]:
X, y = data_load

### Analytic Solution

In [6]:
w = np.linalg.solve(X.T@X, X.T@y)

In [7]:
w

array([ 0.52218765, -3.99766011,  3.65546651, -6.55236882])

It's Wrong!

In [8]:
Z = np.zeros((X.shape[0], X.shape[1]+1))

In [9]:
for i in range(X.shape[0]):
    temp = list(X[i])
    temp.insert(0, 1)  #List.insert(index, value) index에 value값을 넣기
    Z[i] = np.array(temp)

In [10]:
w = np.linalg.solve(Z.T@Z, Z.T@y)

In [11]:
w

array([10.01038492,  2.96479233, -3.99766011,  0.99574142, -7.01707071])

### Gradient Descent

In [33]:
EPOCHS=300
lr=0.00001

In [34]:
Z.shape

(3360, 5)

In [35]:
weights = np.zeros(5)

In [36]:
def forward_pass(X,w):
    return X.dot(w)

In [37]:
def compute_gradient(X,y,w):
    y_hat = forward_pass(X,w)
    return X.T@(y_hat-y)

In [38]:
for _ in range(EPOCHS):
    weights -= lr*compute_gradient(Z,y,weights)

In [39]:
weights

array([ 9.84495223,  2.92013249, -3.99766007,  1.0455666 , -7.00999904])