Pytorch vs Tensorflow
=======
When we run to deep learning code, we use either Tensorflow pakage or Pytorch pakage.

Recently, the number of papers with Pytorch is larger than the number of papers with Tensorflow.

Adaptability with Numpy pakage
---------
Tensorflow pakage is adaptable with Numpy pakage. However, Pytorch pakage isn't.

When we use Pytorch pakage, we need to change type of data. (Tensor not Numpy array)

In [1]:
import tensorflow as tf
import os
import torch
from torch import nn
import numpy as np

In [2]:
a = np.ones((1,25))

In [3]:
model_tf =  tf.keras.models.Sequential()
model_tf.add(tf.keras.Input(25,))
model_tf.add(tf.keras.layers.Dense(16))
model_tf(a)

2022-10-21 10:15:21.005189: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-10-21 10:15:21.005456: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(1, 16), dtype=float32, numpy=
array([[ 1.1699158 , -0.00213276,  0.12879065,  0.8911258 ,  1.2355055 ,
        -0.26317134, -0.32644525, -0.30497113, -0.8705528 , -0.7665633 ,
        -2.0725513 , -0.7568933 , -0.9928194 ,  0.04059547, -1.1255735 ,
        -1.2792699 ]], dtype=float32)>

In [4]:
fc1_torch = nn.Linear(25,16)

In [5]:
fc1_torch(a)

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [6]:
a = np.ones((1,25))
tensor_a = torch.tensor(a, dtype = torch.float32) # Numpy -> Tensor
print(a)
print(type(a))
print(tensor_a)
print(type(tensor_a))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]]
<class 'numpy.ndarray'>
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])
<class 'torch.Tensor'>


In [7]:
#fc1_torch = nn.Linear(25,16)
fc1_torch(tensor_a)

tensor([[ 0.1812,  0.0865, -0.1581, -0.1831,  0.6724, -0.6289,  0.7905,  0.3346,
         -0.2435,  0.3043,  0.7311,  0.0699,  0.6417,  0.3986,  0.8563,  0.7830]],
       grad_fn=<AddmmBackward>)

Tensor
=======
Tensor datatype is similar with Numpy array datatype.

We can operate tensor with similar code.

In [8]:
print(f"Shape of tensor: {tensor_a.shape}")
print(f"Datatype of tensor: {tensor_a.dtype}")
print(f"Device tensor is stored on: {tensor_a.device}")

Shape of tensor: torch.Size([1, 25])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Making Tensor from Numpy array
----------

In [9]:
arr_np = np.random.randn(3,4)
print(arr_np)
print(type(arr_np))
arr_tensor = torch.from_numpy(arr_np)
print(arr_tensor)
print(type(arr_tensor))

[[-1.41502811 -0.75050849  0.66057438  0.59845438]
 [-0.05399175 -1.42132401 -1.58212274 -0.64953701]
 [ 1.70176767 -0.17360025 -0.49828159 -0.11445542]]
<class 'numpy.ndarray'>
tensor([[-1.4150, -0.7505,  0.6606,  0.5985],
        [-0.0540, -1.4213, -1.5821, -0.6495],
        [ 1.7018, -0.1736, -0.4983, -0.1145]], dtype=torch.float64)
<class 'torch.Tensor'>


Making Tensor with random value or constant value
--------

In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)     # Simliar to np.random.rand(shape)
ones_tensor = torch.ones(shape)     # Similar to np.ones(shape)
zeros_tensor = torch.zeros(shape)   # Similar to np.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6846, 0.2368, 0.3512],
        [0.7496, 0.3276, 0.0833]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Device setup
--------
Each tensor has a device which is stored on. ('cpu' or 'cuda')

To operate two (or more) tensors, devices must be same. Furthermore neural network or model must be same.

![error_screenshot](./error.JPG)


In [11]:
print(torch.cuda.is_available())

False


In [12]:
# We move our tensor to the GPU if available

if torch.cuda.is_available():
    rand_tensor = tensor.to("cuda")

print(zeros_tensor + ones_tensor)
print(rand_tensor + ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1.6846, 1.2368, 1.3512],
        [1.7496, 1.3276, 1.0833]])


Indexing and Slicing
-----
We can indexing or slicing tensors similary to Numpy array.

In [13]:
tensor = torch.ones(5, 5)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1., 1.])
tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]])


Combine tensors
-----
 

In [14]:
tensor_l = torch.ones(2,3)
tensor_r = torch.zeros(2,2)
tensor_combined = torch.cat([tensor_l, tensor_r], dim=1)
print(tensor_l)
print(tensor_r)
print(tensor_combined)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]])


Arithmetic operations
-------
Broadcasting

In [15]:
print(tensor_a)
print(tensor_a +1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])
tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.]])


Matrix multiplication

In [16]:
tensor1 = torch.rand((2,3))
tensor2 = torch.rand((3,4))
tensor_prod = tensor1@tensor2
print(tensor1)
print(tensor2)
print(tensor_prod)

tensor([[0.3828, 0.5420, 0.6608],
        [0.9150, 0.9756, 0.9202]])
tensor([[0.4691, 0.4331, 0.2848, 0.7001],
        [0.8825, 0.5670, 0.2898, 0.3171],
        [0.0756, 0.3217, 0.9543, 0.9602]])
tensor([[0.7078, 0.6857, 0.8967, 1.0744],
        [1.3597, 1.2455, 1.4214, 1.8336]])


Tensor -> Other datatype(Numpy array or float)
------
Tensor -> Numpy array

In [17]:
print(rand_tensor)
rand_arr = rand_tensor.numpy()
print(rand_arr)

tensor([[0.6846, 0.2368, 0.3512],
        [0.7496, 0.3276, 0.0833]])
[[0.68463945 0.2368375  0.3511768 ]
 [0.74961644 0.32758498 0.08330113]]


Tensor -> Float

In [18]:
sum = rand_tensor.sum()
print(sum)
print(type(sum))
num = sum.item()
print(num)
print(type(num))

tensor(2.4332)
<class 'torch.Tensor'>
2.4331562519073486
<class 'float'>
