# 넘파이(NumPy) 모듈 이용하기

In [ ]:
import numpy as np

In [ ]:
!pip install numpy

In [1]:
import numpy as np

- `numpy` 모듈을 통해 n-dimensional array를 생성할 수 있습니다. 
- 1차원 array는 벡터, 2차원 array는 행렬에 대응됩니다.
- tensor처럼 생각할 수 있습니다.

In [2]:
x = [1,2,3,4,5,6]

type(x)

list

In [3]:
x = np.array(x)

type(x)

numpy.ndarray

In [4]:
x

array([1, 2, 3, 4, 5, 6])

In [5]:
x.shape

(6,)

In [6]:
x + x

array([ 2,  4,  6,  8, 10, 12])

In [7]:
x - x

array([0, 0, 0, 0, 0, 0])

In [9]:
x*x

array([ 1,  4,  9, 16, 25, 36])

In [8]:
x * 10

array([10, 20, 30, 40, 50, 60])

In [10]:
x / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

In [11]:
y = x.reshape(2,3)

In [12]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A = np.array([[3, 0], [0, 6]])
B = np.array([[2, 3], [2, -3]])

In [14]:
A

array([[3, 0],
       [0, 6]])

In [15]:
B

array([[ 2,  3],
       [ 2, -3]])

In [16]:
# 행렬처럼 보이지만, 실제 행렬계산이 아니라 element-wise multiplication입니다.

A*B

array([[  6,   0],
       [  0, -18]])

In [17]:
# 행렬의 곱
A@B

array([[  6,   9],
       [ 12, -18]])

In [18]:
A.dot(B)

array([[  6,   9],
       [ 12, -18]])

## 사실 `array` 말고도 `matrix`를 만들 수 있다..!

In [19]:
A = np.matrix([[3,0],[0,6]])

In [20]:
A

matrix([[3, 0],
        [0, 6]])

In [21]:
type(A)

numpy.matrix

In [22]:
B = np.matrix('2,3;2,-3')

In [23]:
B

matrix([[ 2,  3],
        [ 2, -3]])

In [24]:
# matrix 형태이므로 정말 matrix 곱하기를 연산합니다.

A*B

matrix([[  6,   9],
        [ 12, -18]])

### 하지만 대부분의 데이터 형태는 모두 `ndarray`형태이므로 딥러닝에서 `matrix`를 이용하는 일은 거의 없습니다.

In [25]:
A = np.array([[3, 0], [0, 6]])

In [26]:
x = np.array([[2],[3]])

x

array([[2],
       [3]])

In [27]:
x.shape

(2, 1)

In [28]:
A@x

array([[ 6],
       [18]])

## 인덱싱 / 슬라이싱

- array에서의 배열 슬라이스는 새로운 객체를 만드는 것이 아닌 원래 배열에 대한 뷰(view)입니다. 
- 즉, 선택 부분의 값을 변경하면 원래 배열의 같은 위치의 값도 변경이 되게 됩니다.
- 새로운 객체를 만들 때에는 `copy()` 메소드를 이용합니다.

In [29]:
arr = np.arange(10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
sub_arr= arr[2:5]

In [32]:
sub_arr

array([2, 3, 4])

In [33]:
sub_arr[0] = 5

In [34]:
sub_arr

array([5, 3, 4])

In [35]:
arr

array([0, 1, 5, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# 일부분을 가져오려면 copy를 이용해야 합니다.

sub_arr2 = arr[2:5].copy()

In [37]:
sub_arr2

array([5, 3, 4])

In [38]:
sub_arr2[0]=2

In [39]:
sub_arr2

array([2, 3, 4])

In [40]:
arr

array([0, 1, 5, 3, 4, 5, 6, 7, 8, 9])

### 2d 이상의 인덱싱

In [41]:
x = np.arange(2, 22, 2)

In [42]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
x = x.reshape(5,2)

In [44]:
x

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [47]:
x.reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [45]:
x[2]

array([10, 12])

In [46]:
x[2].shape

(2,)

In [48]:
y = np.arange(12)
y = y.reshape(2,3,2)

In [51]:
y.reshape(10,1)

ValueError: cannot reshape array of size 12 into shape (10,1)

In [49]:
y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [50]:
y[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
y[0,1,0]

2

## 논리를 이용한 인덱싱

In [53]:
X = np.random.randn(4,5)

X

array([[ 0.17277328,  1.30887728, -0.02359676, -0.85546308, -0.23041994],
       [-0.0582411 ,  0.05071294,  2.68325392, -0.90822892,  1.76729338],
       [-0.62322928, -1.68062633,  0.43344082, -0.81306445,  0.64494777],
       [-0.68884855,  1.79796102,  1.45217499, -1.28814322, -1.44838642]])

In [54]:
y = np.array([0,1,0,1])

In [55]:
y

array([0, 1, 0, 1])

In [56]:
X[y==0]

array([[ 0.17277328,  1.30887728, -0.02359676, -0.85546308, -0.23041994],
       [-0.62322928, -1.68062633,  0.43344082, -0.81306445,  0.64494777]])

## Transpose 

- 전치행렬을 구하거나, 축을 바꿀 때에 사용됩니다.

In [57]:
A = np.arange(15).reshape(3,5)

A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
A.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [59]:
B = np.arange(2*3*4).reshape(2,3,4)

B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [60]:
B.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [61]:
C = B.T
C.shape

(4, 3, 2)

In [62]:
# 원래 dimension에 대한 permutation을 인자로 넣어주면 원하는 축에 대해 바꿀 수 있습니다.

B.transpose((0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

## Broadcast (브로드캐스트)

- 서로 다른 사이즈의 array끼리도, 사이즈가 n배 차이난다면 연산이 가능한데, 이를 브로드캐스트 연산이라고 합니다.

In [63]:
w = np.array([[1,2], [3,4]])
b = np.array([1,10])

In [64]:
w

array([[1, 2],
       [3, 4]])

In [65]:
b

array([ 1, 10])

In [66]:
w*b

array([[ 1, 20],
       [ 3, 40]])

In [67]:
w@b

array([21, 43])

## Pseudorandom Number Generation

- `numpy.random` 모듈을 이용하여 난수를 생성할 수 있습니다.
- 난수 생성은 `seed`와 알고리즘에 의해서 만들어지기 때문에 같은 seed와 알고리즘하에서는 항상 같은 난수가 만들어지기 때문에 **pseudorandom**이라고 부릅니다. 

In [ ]:
np.random.seed(1)

In [ ]:
# shape이 (5,4)가 되는 array를 생성하는데, 각 원소들은 [0,1] uniform 분포에서 추출됩니다.
# 한 번 더 돌려보면?

x = np.random.rand(5,4)
x

In [ ]:
# randn은 평균=0, 표준편차=1인 표준정규분포에서 임의로 추출합니다.

a = np.random.randn(3,2)

In [ ]:
a

- 평균=4, 표준편차=3인 정규분포에서는 어떻게 추출할까요?

    - `np.random.normal(loc=4, scale=3, size=(3,4))`